spring:
  datasource:
    url: jdbc:p6spy:mysql://47.103.100.82:3306/mybatis-plus?serverTimeZone=Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 10